:global:
  componentName: OpenShift4 Console
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - custom-route
      - custom-route-4.7
      - custom-route-legacy
      - custom-route-legacy-4.7
      - custom-route-managed-tls
      - custom-links
      - custom-logo

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
