= Parameters

The parent key for all of the following parameters is `openshift4_console`.

== `openshift_version`

[horizontal]
type:: string
default:: `4.8`

The component uses this parameter to select the appropriate recommended way to configure a custom console hostname.

On OpenShift 4.7 and older, the values provided for parameters `config.route` or `route` are inserted into the `console.operator.openshift.io/cluster` custom resource.

On OpenShift 4.8 and newer, the values provided for the parameters are configured in `spec.componentRoutes` of the `ingress.config.openshift.io/cluster` custom resource.

== `route`

[horizontal]
type:: dictionary
default:: `{"console": {}, "downloads": {}}`

A dictionary holding the configuration for the console and download routes.

The component will look for keys `hostname` and `servingCertKeyPairSecret` in the values of keys `console` and `downloads`.
The component expects that the value of `servingCertKeyPairSecret` is of the form `{"name": "<secret_name>"}` and refers to a secret in namespace `openshift-config`.

== `config`

[horizontal]
type:: dictionary
default:: CRD defaults.

A dictionary holding the `.spec` for the console config.

See the https://docs.openshift.com/container-platform/latest/web_console/customizing-the-web-console.html[OpenShift docs] for available parameters.

=== `config.managementState`

[horizontal]
type:: enum `Managed`, `Unmanaged`, `Removed`
default:: `Managed`

Indicates whether and how the operator should manage the console.

=== `config.route`

[horizontal]
type:: dictionary with `hostname` and `secret` keys
default:: undefined

Create a custom route to access the console.
If the route is part of the default apps domain, no TLS cert needs to be specified since the default wildcard cert will be used.

[IMPORTANT]
====
This configuration parameter is deprecated starting with OpenShift 4.8, see the https://docs.openshift.com/container-platform/4.8/web_console/customizing-the-web-console.html#customizing-the-console-route_customizing-web-console[upstream documentation].

The component provides support to use the new recommended configuration via the `ingress.config.openshift.io/cluster` object, see the documentation for parameters <<_openshift_version,`openshift_version`>> and <<_route,`route`>>.

If both this parameter and parameter `route` are present, parameter `route` has precedence over this parameter.
====

== `console_links`

[horizontal]
type:: dictionary
default:: `{}`

Each entry in parameter `console_links` is deployed onto the cluster as an https://docs.openshift.com/container-platform/4.9/web_console/customizing-the-web-console.html#creating-custom-links_customizing-web-console[OpenShift `ConsoleLink`].
The value of the entry will be used as the `ConsoleLink` specification.
Entries with `null` values are skipped.
This allows users to remove links which were configured higher up in the hierarchy.

== `custom_logo`

[horizontal]
type:: dictionary
default:: `{}`

Add a custom logo to the console.
Takes a single key with the filename and the value is the base64 encoded logo.
The logo can be a file in any common image format, including GIF, JPG, PNG, or SVG, and is constrained to a max-height of 60px
The filename needs to have a filename extension which matches the image format.

[NOTE]
====
For SVG logos the file must *not* be base64 encoded, but inserted directly as a string.
====

== `secrets`

[horizontal]
type:: dictionary
default:: `{}`

Each entry in parameter `secrets` is deployed onto the cluster as a Kubernetes Secret with `type=kubernetes.io/tls`.
Entries with `null` values are skipped.
This allows users to remove secrets which were configured higher up in the hierarchy.

The component has basic validation to ensure the secret contents are a plausible Kubernetes TLS secret.

The dictionary keys are used as `metadata.name` for the resulting `Secret` resources.
The dictionary values are directly merged into a `Secret` resource which only has `type=kubernetes.io/tls` set.
The secrets are created in the namespace indicated by parameter `namespace`.

== `cert_manager_certs`

[horizontal]
type:: dictionary
default:: `{}`

Each entry in parameter `cert_manager_certs` is deployed onto the cluster as a cert-manager `Certificate` resource.
Entries with `null` values are skipped.
This allows users to remove certificates which were configured higher up in the hierarchy.

The dictionary keys are used as `metadata.name` and `spec.secretName` for the resulting `Certificate` resources.
The dictionary values are then directly directly merged into the mostly empty `Certificate` resources.


== Example: Custom hostname in cluster's app domain

[source,yaml]
----
openshift4_console:
  route:
    console:
      hostname: console.apps.example.com
----

=== Example: Custom hostname outside cluster's app domain

In this case we need to specify a custom certificate:

[source,yaml]
----
openshift4_console:
  route:
    console:
      hostname: console.cluster.example.com
      servingCertKeyPairSecret:
        name: console-cluster-example-com-tls <1>
  secrets:
    console-cluster-example-com-tls:
      stringData:
        tls.crt: ?{vaultkv:${cluster:tenant}/${cluster:name}/openshift4-console/certificates/cert} <2>
        tls.key: ?{vaultkv:${cluster:tenant}/${cluster:name}/openshift4-console/certificates/key} <3>
----
<1> A secret with keys `tls.crt` and `tls.key` with this name must exist in namespace `openshift-config`.
<2> Reference to the console hostname TLS certificate in Vault
<3> Reference to the console hostname TLS private key in Vault

=== Example: Custom hostname outside cluster's app domain with cert-manager certificate

This configuration assumes that the DNS record for `console.cluster.example.com` points to the cluster's application LBs, ideally as a CNAME to the cluster's application domain.
This is required so that cert-manager can request the Let's Encrypt certificate using a HTTP01 challenge.

[source,yaml]
----
openshift4_console:
  route:
    console:
      hostname: console.cluster.example.com
      servingCertKeyPairSecret:
        name: console-cluster-example-com-tls <1>
  cert_manager_certs:
    console-cluster-example-com-tls:
      spec:
        dnsNames:
          - console.cluster.example.com
        issuerRef:
          name: letsencrypt-production
          kind: ClusterIssuer
----


=== Example: Custom links and logo in the web console

[source,yaml]
----
openshift4_console:
  console_links:
    homepage: <1>
      href: 'https://www.example.com/'
      location: ApplicationMenu
      text: Home
      applicationMenu:
        section: Company
        # image that is 24x24 in size
        imageURL: https://via.placeholder.com/24
    user-docs: <2>
      href: 'https://docs.example.com/'
      location: HelpMenu
      text: User Documentation
    project-link: <3>
      href: 'https://docs.example.com/organization/'
      location: HelpMenu
      text: User Documentation
      namespaceDashboard:
        matchExpressions:
         - key: organization
           operation: Exists
  custom_logo:
    logo.png: |- <4>
      <base64-encoded_logo>
----
<1> Adds a link to an overflow menu at the top of every page
<2> Adds a link to the help menu at the top of every page
<3> Adds a link to the dashboard of every namespace with a label `organization`
<4> Provide a single base64-encoded logo and the key needs to have the correct filename extension
